name: Whitelist4qq
version: '${project.version}'
main: ltd.teaparty.whitelist4qq.Whitelist4qq
api-version: '1.20'
depend: [ MiraiMC ]
commands:
  whitelist4qq:
    description: Whitelist4QQ main command.
    permission: whitelist4qq.command.whitelist4qq
    aliases:
      - qwhitelist
      - qwl
permissions:
  whitelist4qq.*:
    default: op
    children:
      whitelist4qq.command.*:
        default: op
        children:
          whitelist4qq.show:
            description: Allow use /whitelist4qq
            default: true