
# 插件配置
general:
  Mysql_url: "jdbc:mysql://192.168.1.103:3306/bind_qq"
  Mysql_user: "bind_qq"
  Mysql_password: "bind_qq"
  # 踢出信息。在踢出不在 MiraiMC 数据库的玩家时显示的踢出消息
  # 默认提示消息使用的是 YAML 换行符，如果想使用单行消息可以设为 kick-message: "消息内容"
  kick-message: |-
    &c你不在本服的白名单中，请加入我们的QQ群进行申请
    &cQQ群：340902274

# 机器人配置
bot:
  # 用于接收验证的 QQ，只有存在于以下列表的机器人 QQ 的消息才会被处理
  # 请至少填写一个
  used-bot-accounts:
    - 3334351832

  # 用于接收验证的 QQ 群，只有存在于以下列表的 QQ 群的消息才会被处理
  # 请至少填写一个
  used-group-numbers:
    - 927135602
    - 340902274

  # 让 Whitelist4QQ 处理 QQ 群内的绑定命令消息
  # 如果启用，请勿安装 Link2QQ 插件，避免玩家通过 Link2QQ 插件更换绑定从而绕过服务器管理员的审查
  # 如果禁用，除非管理员手动为玩家添加绑定，否则玩家将无法自行绑定 QQ，也就无法获得白名单
  use-group-message-command: true

  # 添加绑定消息前缀
  # 玩家需要发送“消息前缀+自己的ID”才会添加绑定
  # 例如：下方设置为“申请白名单”，玩家的ID是“123456”，则玩家需要在群内发送消息“申请白名单123456”
  bind-command-prefix: "申请白名单"

  # 消息
  # 插件向群内发送的所有消息都在这里配置
  messages:
    # 绑定成功
    bind-success: "已绑定成功"

    # 绑定失败
    # 无论绑定失败的原因是什么，都只会发这一条
    # 可用变量：%id% - QQ绑定的ID（use-self-data为true时不可用）
    bind-failed: |-
      绑定失败，此ID可能已经绑定另一个QQ，或你的QQ已经绑定了一个ID，请联系管理员处理！
      此QQ绑定的ID：%id%